### ISSUE TITLE
Create Upgrade for sylius v1.11.0

### ISSUE THREAD

**Issue by tsogoo** [davidroberto/-NOT-MAINTAINED-sylius-next-boilerplate-theme#3]
If you create a new branch for sylius v1.11.0 I'm happy to create a pull request. Order completion works for customer without login. I didn't test it to logged in user.

**Comment by davidroberto** [comment]
Here you go! https://github.com/davidroberto/sylius-next-boilerplate-theme/tree/release/v1.1.0
